# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: libsql
    hostname: libsql
    ports:
      - 5001:5001
      - 8080:8080
    volumes:
      - libsql_data:/var/lib/sqld
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    ports:
      - '1025:1025' # port the SMTP server should be accessible on
      - '8025:8025' # port the web interface should be accessible on
    environment:
      # https://github.com/axllent/mailpit/wiki/Runtime-options
      TZ: 'Asia/Jakarta'

volumes:
  libsql_data:
    driver: local
  mailpit_data:
    driver: local
